import { TOKEN_PATTERN } from "@webmcp-cloud-relay/protocol";
export { Bridge } from "./bridge";

export interface Env {
  BRIDGE: DurableObjectNamespace;
}

/**
 * Routes:
 *   GET  /t/:token/ws   - extension WebSocket
 *   POST /t/:token/mcp  - MCP streamable HTTP (also GET for SSE, DELETE)
 *
 * The token is a bearer capability generated by the extension; the Durable
 * Object is addressed by its SHA-256 hash, so the relay stores no account
 * data and unknown tokens simply land in empty bridges.
 */
export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/") return new Response("webmcp-cloud-relay");
    const match = url.pathname.match(/^\/t\/([^/]+)\/(ws|mcp)$/);
    if (!match) return new Response("Not found", { status: 404 });
    const [, token, endpoint] = match;
    if (!token || !TOKEN_PATTERN.test(token)) {
      return new Response("Invalid token", { status: 404 });
    }
    const digest = await crypto.subtle.digest(
      "SHA-256",
      new TextEncoder().encode(token),
    );
    const name = [...new Uint8Array(digest)]
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
    const stub = env.BRIDGE.get(env.BRIDGE.idFromName(name));
    return stub.fetch(
      new Request(new URL(`/${endpoint}`, url.origin), request),
    );
  },
};
